# Generated by Django 3.1.2 on 2020-11-23 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('address', models.TextField(default='None', max_length=250)),
                ('age', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(default='images/iitbhu.png', upload_to='images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Car', 'Car'), ('Scooty', 'Scooty'), ('Motorbike', 'Motorbike')], max_length=20)),
                ('km_driven', models.PositiveIntegerField()),
                ('pic', models.ImageField(default='images/iitbhu.png', upload_to='images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('TOBECOMPLETED', 'ToBeCompleted')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('km_drove', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('borrower', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.person')),
                ('lender', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rentalapp.person')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle')),
            ],
        ),
    ]
