# Generated by Django 3.1.2 on 2020-11-02 07:30

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('km_driven', models.PositiveIntegerField()),
                ('per_km_cost', models.PositiveIntegerField(default=12)),
                ('per_day_cost', models.PositiveIntegerField(default=500)),
                ('availability_start_date', models.DateField()),
                ('availability_end_date', models.DateField(null=True)),
                ('category', models.CharField(choices=[('CAR', 'Car'), ('SCOOTY', 'Scooty'), ('MOTORBIKE', 'MotorBike')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('TOBECOMPLETED', 'ToBeCompleted')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('km_drove', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle')),
            ],
        ),
    ]
