# Generated by Django 3.1.2 on 2020-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='per_day_cost',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='bookings',
            name='per_km_cost',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='km_drove',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('BOOKED', 'Booked'), ('Available', 'AVAILABLE')], max_length=20),
        ),
    ]
