# Generated by Django 3.1.2 on 2020-11-02 07:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='borrower',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.borrower'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='lender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.lender'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.lender'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
