# Generated by Django 3.1.2 on 2020-11-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_auto_20201123_1053'),
        ('rentalapp', '0002_auto_20201123_1149'),
    ]

    operations = [
    ]
