# Generated by Django 3.1.2 on 2020-11-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_auto_20201102_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drop_address',
            field=models.CharField(default=models.CharField(default='abcd', max_length=200), max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_address',
            field=models.CharField(default='abcd', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
