# Generated by Django 3.1.2 on 2020-11-21 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentalapp', '0003_auto_20201102_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='lender',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drop_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('address', models.TextField(default='None', max_length=250)),
                ('age', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='borrower',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.person'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.person'),
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
    ]
