# Generated by Django 3.1.2 on 2020-11-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_merge_20201123_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('BOOKED', 'Booked'), ('Available', 'AVAILABLE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pic',
            field=models.ImageField(default='/static/images/iitbhu.png', upload_to='./static/images'),
        ),
    ]
