# Generated by Django 3.1.3 on 2020-11-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_merge_20201123_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pic',
            field=models.ImageField(default='/static/images/iitbhu.png', upload_to='./static/images'),
        ),
    ]
