# Generated by Django 3.1.3 on 2020-11-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_auto_20201123_1407'),
        ('rentalapp', '0004_auto_20201123_1406'),
    ]

    operations = [
    ]
