# Generated by Django 3.1.2 on 2020-11-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_auto_20201121_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rentalapp.person'),
        ),
    ]
