# Generated by Django 3.1.2 on 2020-11-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_auto_20201123_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.person'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rentalapp.person'),
        ),
    ]
