# Generated by Django 3.1.3 on 2020-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_auto_20201123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
