# Generated by Django 3.1.3 on 2020-11-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_auto_20201123_1447'),
        ('rentalapp', '0008_auto_20201123_1836'),
    ]

    operations = [
    ]
