# Generated by Django 3.1.2 on 2020-11-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0009_merge_20201123_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='cost',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
