# Generated by Django 3.1.2 on 2020-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0010_auto_20201121_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='images/iitbhu.png', upload_to='images'),
        ),
    ]
