# Generated by Django 3.1.2 on 2020-11-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0011_auto_20201124_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rentalapp.person'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPELETED'), ('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=20),
        ),
    ]
