# Generated by Django 3.2.6 on 2021-08-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0012_auto_20201124_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='static/images/iitbhu.png', upload_to='./static/images'),
        ),
    ]
