# Generated by Django 3.1.2 on 2020-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0012_auto_20201122_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('Scooty', 'Scooty'), ('Motorbike', 'Motorbike')], max_length=20),
        ),
    ]
