# Generated by Django 3.2.6 on 2021-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0014_alter_person_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='static/images/iitbhu.jpeg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pic',
            field=models.ImageField(default='static/images/iitbhu.jpeg', upload_to='static/images'),
        ),
    ]
