# Generated by Django 3.1.2 on 2020-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0014_auto_20201122_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(default='DL5ACC1234', max_length=100, primary_key=True, serialize=False),
        ),
    ]
